version: "3"
services:
  web:
    hostname: ma0-tdi-php-apache
    build: .
    ports:
      - 80:80
    networks:
      - backend
      - frontend
    environment:
      BUGZILLA_DB_HOST: ma0-tdi-mariadb
      BUGZILLA_DB_LOGIN: bugs
      BUGZILLA_DB_PASS: My12Bugs34
      BUGZILLA_DB_NAME: bugs
      SERVERADMIN_EMAIL: webmaster@foo.com
      SERVERNAME: http://bugzilla.it1.eur.aruba.jenv-aruba.cloud
      BUGZILLA_ADMIN_EMAIL: webmaster@foo.com
      BUGZILLA_ADMIN_PASS: 
      BUGZILLA_ADMIN_REALNAME: luckezilla
    depends_on:
      - db
  db:
    hostname: ma0-tdi-mariadb
    image: mariadb
    container_name: ma0-tdi-mariadb
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    environment:
      MYSQL_ROOT_PASSWORD: My12Pass34
      MYSQL_DATABASE: bugs
      MYSQL_USER: bugs
      MYSQL_PASSWORD: My12Bugs34
    ports:
      - 3306:3306
networks:
  backend:
  frontend:
